# Generated by Django 5.1.1 on 2024-11-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_service", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TokenModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
