# Generated by Django 5.1.6 on 2025-02-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_service', '0003_authenticationstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticationstate',
            name='state',
            field=models.TextField(),
        ),
    ]
  
