# Generated by Django 5.1.1 on 2024-11-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_service", "0002_tokenmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthenticationState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
